"""add ingestion runs

Revision ID: 21054fc5a0ae
Revises: 68ba7cb8a997
Create Date: 2026-03-08 20:36:32.770620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21054fc5a0ae'
down_revision: Union[str, Sequence[str], None] = '68ba7cb8a997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.create_index('ix_ingestion_run_job_started', ['job_name', 'started_at'], unique=False)
        batch_op.create_index('ix_ingestion_run_status_started', ['status', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_runs_started_at'), ['started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_started_at'))
        batch_op.drop_index('ix_ingestion_run_status_started')
        batch_op.drop_index('ix_ingestion_run_job_started')

    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
