"""add canonical ingestion foundation

Revision ID: 47555eda0919
Revises: 21054fc5a0ae
Create Date: 2026-03-08 21:23:28.205386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47555eda0919'
down_revision: Union[str, Sequence[str], None] = '21054fc5a0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index('ix_player_full_name', ['full_name'], unique=False)

    op.create_table('source_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('payload_type', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_payloads', schema=None) as batch_op:
        batch_op.create_index('ix_source_payload_external', ['source', 'external_id', 'captured_at'], unique=False)
        batch_op.create_index('ix_source_payload_lookup', ['source', 'payload_type', 'captured_at'], unique=False)

    op.create_table('teams',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('conference', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index('ix_team_abbreviation', ['abbreviation'], unique=False)

    op.create_table('games',
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('game_date', sa.DateTime(), nullable=True),
    sa.Column('home_team_id', sa.String(), nullable=True),
    sa.Column('away_team_id', sa.String(), nullable=True),
    sa.Column('home_team_abbreviation', sa.String(), nullable=True),
    sa.Column('away_team_abbreviation', sa.String(), nullable=True),
    sa.Column('game_status', sa.Integer(), nullable=True),
    sa.Column('status_text', sa.String(), nullable=True),
    sa.Column('game_time_utc', sa.DateTime(), nullable=True),
    sa.Column('is_in_season_tournament', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index('ix_games_season_date', ['season', 'game_date'], unique=False)
        batch_op.create_index('ix_games_status_date', ['game_status', 'game_date'], unique=False)

    op.create_table('ingestion_run_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_key', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_run_items', schema=None) as batch_op:
        batch_op.create_index('ix_ingestion_run_item_run_stage', ['run_id', 'stage', 'created_at'], unique=False)
        batch_op.create_index('ix_ingestion_run_item_status', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingestion_run_items', schema=None) as batch_op:
        batch_op.drop_index('ix_ingestion_run_item_status')
        batch_op.drop_index('ix_ingestion_run_item_run_stage')

    op.drop_table('ingestion_run_items')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index('ix_games_status_date')
        batch_op.drop_index('ix_games_season_date')

    op.drop_table('games')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index('ix_team_abbreviation')

    op.drop_table('teams')
    with op.batch_alter_table('source_payloads', schema=None) as batch_op:
        batch_op.drop_index('ix_source_payload_lookup')
        batch_op.drop_index('ix_source_payload_external')

    op.drop_table('source_payloads')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index('ix_player_full_name')

    op.drop_table('players')
    # ### end Alembic commands ###
