"""initial schema

Revision ID: 68ba7cb8a997
Revises: 
Create Date: 2026-03-08 20:12:13.947578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ba7cb8a997'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_advanced_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('usage_percentage', sa.Float(), nullable=True),
    sa.Column('estimated_usage_percentage', sa.Float(), nullable=True),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.Column('pace_per40', sa.Float(), nullable=True),
    sa.Column('possessions', sa.Float(), nullable=True),
    sa.Column('offensive_rating', sa.Float(), nullable=True),
    sa.Column('defensive_rating', sa.Float(), nullable=True),
    sa.Column('net_rating', sa.Float(), nullable=True),
    sa.Column('true_shooting_percentage', sa.Float(), nullable=True),
    sa.Column('effective_field_goal_percentage', sa.Float(), nullable=True),
    sa.Column('assist_percentage', sa.Float(), nullable=True),
    sa.Column('assist_to_turnover', sa.Float(), nullable=True),
    sa.Column('offensive_rebound_percentage', sa.Float(), nullable=True),
    sa.Column('defensive_rebound_percentage', sa.Float(), nullable=True),
    sa.Column('pie', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('touches', sa.Float(), nullable=True),
    sa.Column('passes', sa.Float(), nullable=True),
    sa.Column('secondary_assists', sa.Float(), nullable=True),
    sa.Column('free_throw_assists', sa.Float(), nullable=True),
    sa.Column('rebound_chances_offensive', sa.Float(), nullable=True),
    sa.Column('rebound_chances_defensive', sa.Float(), nullable=True),
    sa.Column('rebound_chances_total', sa.Float(), nullable=True),
    sa.Column('contested_field_goals_made', sa.Float(), nullable=True),
    sa.Column('contested_field_goals_attempted', sa.Float(), nullable=True),
    sa.Column('uncontested_field_goals_made', sa.Float(), nullable=True),
    sa.Column('uncontested_field_goals_attempted', sa.Float(), nullable=True),
    sa.Column('defended_at_rim_field_goals_made', sa.Float(), nullable=True),
    sa.Column('defended_at_rim_field_goals_attempted', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_historical_advanced_player_game')
    )
    with op.batch_alter_table('historical_advanced_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_advanced_logs_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_advanced_logs_player_id'), ['player_id'], unique=False)
        batch_op.create_index('ix_historical_advanced_player_game', ['player_id', 'game_id'], unique=False)

    op.create_table('historical_game_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('opponent', sa.String(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('rebounds', sa.Float(), nullable=True),
    sa.Column('assists', sa.Float(), nullable=True),
    sa.Column('steals', sa.Float(), nullable=True),
    sa.Column('blocks', sa.Float(), nullable=True),
    sa.Column('turnovers', sa.Float(), nullable=True),
    sa.Column('threes_made', sa.Float(), nullable=True),
    sa.Column('threes_attempted', sa.Float(), nullable=True),
    sa.Column('field_goals_made', sa.Float(), nullable=True),
    sa.Column('field_goals_attempted', sa.Float(), nullable=True),
    sa.Column('free_throws_made', sa.Float(), nullable=True),
    sa.Column('free_throws_attempted', sa.Float(), nullable=True),
    sa.Column('plus_minus', sa.Float(), nullable=True),
    sa.Column('fantasy_points', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_historical_game_log_player_game')
    )
    with op.batch_alter_table('historical_game_logs', schema=None) as batch_op:
        batch_op.create_index('ix_historical_game_log_player_date', ['player_id', 'game_date'], unique=False)
        batch_op.create_index('ix_historical_game_log_team_date', ['team', 'game_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_game_logs_game_date'), ['game_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_game_logs_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_game_logs_player_id'), ['player_id'], unique=False)

    op.create_table('live_game_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('home_team_id', sa.String(), nullable=False),
    sa.Column('away_team_id', sa.String(), nullable=False),
    sa.Column('home_team_score', sa.Integer(), nullable=True),
    sa.Column('away_team_score', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('game_clock', sa.String(), nullable=True),
    sa.Column('game_status', sa.Integer(), nullable=True),
    sa.Column('status_text', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_game_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_live_game_snapshot_game_time', ['game_id', 'captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_game_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_game_snapshots_game_id'), ['game_id'], unique=False)

    op.create_table('live_player_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('rebounds', sa.Float(), nullable=True),
    sa.Column('assists', sa.Float(), nullable=True),
    sa.Column('steals', sa.Float(), nullable=True),
    sa.Column('blocks', sa.Float(), nullable=True),
    sa.Column('turnovers', sa.Float(), nullable=True),
    sa.Column('field_goals_made', sa.Float(), nullable=True),
    sa.Column('field_goals_attempted', sa.Float(), nullable=True),
    sa.Column('threes_made', sa.Float(), nullable=True),
    sa.Column('threes_attempted', sa.Float(), nullable=True),
    sa.Column('free_throws_made', sa.Float(), nullable=True),
    sa.Column('free_throws_attempted', sa.Float(), nullable=True),
    sa.Column('fouls', sa.Float(), nullable=True),
    sa.Column('plus_minus', sa.Float(), nullable=True),
    sa.Column('on_court', sa.Boolean(), nullable=True),
    sa.Column('starter', sa.Boolean(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_player_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_live_player_snapshot_player_time', ['game_id', 'player_id', 'captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_player_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_player_snapshots_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_player_snapshots_player_id'), ['player_id'], unique=False)

    op.create_table('model_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('market_phase', sa.String(), nullable=False),
    sa.Column('sportsbook', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('stat_type', sa.String(), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('projected_value', sa.Float(), nullable=False),
    sa.Column('over_probability', sa.Float(), nullable=True),
    sa.Column('under_probability', sa.Float(), nullable=True),
    sa.Column('edge_over', sa.Float(), nullable=True),
    sa.Column('edge_under', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('recommended_side', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_signals', schema=None) as batch_op:
        batch_op.create_index('ix_model_signal_lookup', ['game_id', 'player_id', 'stat_type', 'market_phase', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_signals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_signals_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_signals_player_id'), ['player_id'], unique=False)

    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('stat_type', sa.String(), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('over_odds', sa.Integer(), nullable=False),
    sa.Column('under_odds', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('market_phase', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_odds_snapshot_lookup', ['game_id', 'player_id', 'stat_type', 'captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_snapshots_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_snapshots_player_id'), ['player_id'], unique=False)

    op.create_table('player_prop_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('opponent', sa.String(), nullable=True),
    sa.Column('stat_type', sa.String(), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('over_odds', sa.Integer(), nullable=False),
    sa.Column('under_odds', sa.Integer(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', 'stat_type', 'is_live', name='uq_player_prop_snapshot_market')
    )
    with op.batch_alter_table('player_prop_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_player_prop_snapshot_lookup', ['game_id', 'player_id', 'stat_type', 'is_live'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_prop_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_prop_snapshots_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_prop_snapshots_player_id'), ['player_id'], unique=False)

    op.create_table('sportsbook_event_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sportsbook', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('nba_game_id', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sportsbook', 'event_id', name='uq_sportsbook_event_map')
    )
    with op.batch_alter_table('sportsbook_event_maps', schema=None) as batch_op:
        batch_op.create_index('ix_sportsbook_event_map_lookup', ['sportsbook', 'nba_game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sportsbook_event_maps_nba_game_id'), ['nba_game_id'], unique=False)

    op.create_table('team_defensive_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('defensive_rating', sa.Float(), nullable=True),
    sa.Column('estimated_defensive_rating', sa.Float(), nullable=True),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.Column('estimated_pace', sa.Float(), nullable=True),
    sa.Column('opponent_points_per_game', sa.Float(), nullable=True),
    sa.Column('opponent_field_goal_percentage', sa.Float(), nullable=True),
    sa.Column('opponent_three_point_percentage', sa.Float(), nullable=True),
    sa.Column('d_fg_pct_overall', sa.Float(), nullable=True),
    sa.Column('defended_field_goal_attempts', sa.Float(), nullable=True),
    sa.Column('normal_fg_pct_overall', sa.Float(), nullable=True),
    sa.Column('d_pct_plusminus_overall', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season', name='uq_team_defensive_stat_team_season')
    )
    with op.batch_alter_table('team_defensive_stats', schema=None) as batch_op:
        batch_op.create_index('ix_team_defensive_stat_season', ['season', 'team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_defensive_stats_team_id'), ['team_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('team_defensive_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_defensive_stats_team_id'))
        batch_op.drop_index('ix_team_defensive_stat_season')

    op.drop_table('team_defensive_stats')
    with op.batch_alter_table('sportsbook_event_maps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sportsbook_event_maps_nba_game_id'))
        batch_op.drop_index('ix_sportsbook_event_map_lookup')

    op.drop_table('sportsbook_event_maps')
    with op.batch_alter_table('player_prop_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_prop_snapshots_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_prop_snapshots_game_id'))
        batch_op.drop_index(batch_op.f('ix_player_prop_snapshots_captured_at'))
        batch_op.drop_index('ix_player_prop_snapshot_lookup')

    op.drop_table('player_prop_snapshots')
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_player_id'))
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_game_id'))
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_captured_at'))
        batch_op.drop_index('ix_odds_snapshot_lookup')

    op.drop_table('odds_snapshots')
    with op.batch_alter_table('model_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_signals_player_id'))
        batch_op.drop_index(batch_op.f('ix_model_signals_game_id'))
        batch_op.drop_index(batch_op.f('ix_model_signals_created_at'))
        batch_op.drop_index('ix_model_signal_lookup')

    op.drop_table('model_signals')
    with op.batch_alter_table('live_player_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_player_snapshots_player_id'))
        batch_op.drop_index(batch_op.f('ix_live_player_snapshots_game_id'))
        batch_op.drop_index(batch_op.f('ix_live_player_snapshots_captured_at'))
        batch_op.drop_index('ix_live_player_snapshot_player_time')

    op.drop_table('live_player_snapshots')
    with op.batch_alter_table('live_game_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_game_snapshots_game_id'))
        batch_op.drop_index(batch_op.f('ix_live_game_snapshots_captured_at'))
        batch_op.drop_index('ix_live_game_snapshot_game_time')

    op.drop_table('live_game_snapshots')
    with op.batch_alter_table('historical_game_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_game_logs_player_id'))
        batch_op.drop_index(batch_op.f('ix_historical_game_logs_game_id'))
        batch_op.drop_index(batch_op.f('ix_historical_game_logs_game_date'))
        batch_op.drop_index('ix_historical_game_log_team_date')
        batch_op.drop_index('ix_historical_game_log_player_date')

    op.drop_table('historical_game_logs')
    with op.batch_alter_table('historical_advanced_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_historical_advanced_player_game')
        batch_op.drop_index(batch_op.f('ix_historical_advanced_logs_player_id'))
        batch_op.drop_index(batch_op.f('ix_historical_advanced_logs_game_id'))

    op.drop_table('historical_advanced_logs')
    # ### end Alembic commands ###
