"""add extended nba stats ingestion tables

Revision ID: f4a95813c268
Revises: b8c9d0e1f2a3
Create Date: 2026-03-19 23:41:29.157766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a95813c268'
down_revision: Union[str, Sequence[str], None] = 'b8c9d0e1f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hustle_stats_boxscores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('contested_shots_2pt', sa.Float(), nullable=True),
    sa.Column('contested_shots_3pt', sa.Float(), nullable=True),
    sa.Column('contested_shots', sa.Float(), nullable=True),
    sa.Column('deflections', sa.Float(), nullable=True),
    sa.Column('charges_drawn', sa.Float(), nullable=True),
    sa.Column('screen_assists', sa.Float(), nullable=True),
    sa.Column('screen_ast_pts', sa.Float(), nullable=True),
    sa.Column('loose_balls_recovered_offensive', sa.Float(), nullable=True),
    sa.Column('loose_balls_recovered_defensive', sa.Float(), nullable=True),
    sa.Column('loose_balls_recovered', sa.Float(), nullable=True),
    sa.Column('box_outs_offensive', sa.Float(), nullable=True),
    sa.Column('box_outs_defensive', sa.Float(), nullable=True),
    sa.Column('box_outs', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_hustle_stats_boxscore_game_player')
    )
    with op.batch_alter_table('hustle_stats_boxscores', schema=None) as batch_op:
        batch_op.create_index('ix_hustle_stats_boxscore_player_game', ['player_id', 'game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hustle_stats_boxscores_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hustle_stats_boxscores_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hustle_stats_boxscores_team_id'), ['team_id'], unique=False)

    op.create_table('lineup_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('team_abbreviation', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('gp', sa.Integer(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('off_rating', sa.Float(), nullable=True),
    sa.Column('def_rating', sa.Float(), nullable=True),
    sa.Column('net_rating', sa.Float(), nullable=True),
    sa.Column('ast_pct', sa.Float(), nullable=True),
    sa.Column('ast_to', sa.Float(), nullable=True),
    sa.Column('ast_ratio', sa.Float(), nullable=True),
    sa.Column('oreb_pct', sa.Float(), nullable=True),
    sa.Column('dreb_pct', sa.Float(), nullable=True),
    sa.Column('reb_pct', sa.Float(), nullable=True),
    sa.Column('tov_pct', sa.Float(), nullable=True),
    sa.Column('efg_pct', sa.Float(), nullable=True),
    sa.Column('ts_pct', sa.Float(), nullable=True),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.Column('pie', sa.Float(), nullable=True),
    sa.Column('plus_minus', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'season', name='uq_lineup_stats_group_season')
    )
    with op.batch_alter_table('lineup_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lineup_stats_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lineup_stats_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_lineup_stats_team_id'), ['team_id'], unique=False)
        batch_op.create_index('ix_lineup_stats_team_season_group', ['team_id', 'season', 'group_id'], unique=False)

    op.create_table('matchup_boxscores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('offense_player_id', sa.String(), nullable=False),
    sa.Column('offense_player_name', sa.String(), nullable=False),
    sa.Column('defense_player_id', sa.String(), nullable=False),
    sa.Column('defense_player_name', sa.String(), nullable=False),
    sa.Column('matchup_minutes', sa.Float(), nullable=True),
    sa.Column('matchup_minutes_sort', sa.Float(), nullable=True),
    sa.Column('partial_possessions', sa.Float(), nullable=True),
    sa.Column('player_points', sa.Float(), nullable=True),
    sa.Column('switches_on', sa.Float(), nullable=True),
    sa.Column('matchup_field_goals_made', sa.Float(), nullable=True),
    sa.Column('matchup_field_goals_attempted', sa.Float(), nullable=True),
    sa.Column('matchup_field_goal_percentage', sa.Float(), nullable=True),
    sa.Column('matchup_assists', sa.Float(), nullable=True),
    sa.Column('matchup_turnovers', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'offense_player_id', 'defense_player_id', name='uq_matchup_boxscore_game_players')
    )
    with op.batch_alter_table('matchup_boxscores', schema=None) as batch_op:
        batch_op.create_index('ix_matchup_boxscore_game_defense', ['game_id', 'defense_player_id'], unique=False)
        batch_op.create_index('ix_matchup_boxscore_game_offense', ['game_id', 'offense_player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matchup_boxscores_defense_player_id'), ['defense_player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matchup_boxscores_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matchup_boxscores_offense_player_id'), ['offense_player_id'], unique=False)

    op.create_table('player_clutch_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('team_abbreviation', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('clutch_time', sa.String(), nullable=False),
    sa.Column('point_diff', sa.Integer(), nullable=False),
    sa.Column('gp', sa.Integer(), nullable=True),
    sa.Column('w', sa.Integer(), nullable=True),
    sa.Column('l', sa.Integer(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('fgm', sa.Float(), nullable=True),
    sa.Column('fga', sa.Float(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('fg3m', sa.Float(), nullable=True),
    sa.Column('fg3a', sa.Float(), nullable=True),
    sa.Column('fg3_pct', sa.Float(), nullable=True),
    sa.Column('ftm', sa.Float(), nullable=True),
    sa.Column('fta', sa.Float(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.Column('oreb', sa.Float(), nullable=True),
    sa.Column('dreb', sa.Float(), nullable=True),
    sa.Column('reb', sa.Float(), nullable=True),
    sa.Column('ast', sa.Float(), nullable=True),
    sa.Column('tov', sa.Float(), nullable=True),
    sa.Column('stl', sa.Float(), nullable=True),
    sa.Column('blk', sa.Float(), nullable=True),
    sa.Column('pf', sa.Float(), nullable=True),
    sa.Column('pts', sa.Float(), nullable=True),
    sa.Column('plus_minus', sa.Float(), nullable=True),
    sa.Column('nba_fantasy_pts', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'clutch_time', 'point_diff', name='uq_player_clutch_stats_key')
    )
    with op.batch_alter_table('player_clutch_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_clutch_stats_player_id'), ['player_id'], unique=False)
        batch_op.create_index('ix_player_clutch_stats_player_season', ['player_id', 'season'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_clutch_stats_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_clutch_stats_team_id'), ['team_id'], unique=False)
        batch_op.create_index('ix_player_clutch_stats_team_season', ['team_id', 'season'], unique=False)

    op.create_table('player_defensive_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('team_abbreviation', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('defense_category', sa.String(), nullable=False),
    sa.Column('gp', sa.Integer(), nullable=True),
    sa.Column('g', sa.Integer(), nullable=True),
    sa.Column('freq', sa.Float(), nullable=True),
    sa.Column('d_fgm', sa.Float(), nullable=True),
    sa.Column('d_fga', sa.Float(), nullable=True),
    sa.Column('d_fg_pct', sa.Float(), nullable=True),
    sa.Column('normal_fg_pct', sa.Float(), nullable=True),
    sa.Column('pct_plusminus', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'defense_category', name='uq_player_defensive_tracking_key')
    )
    with op.batch_alter_table('player_defensive_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_defensive_tracking_player_id'), ['player_id'], unique=False)
        batch_op.create_index('ix_player_defensive_tracking_player_season_category', ['player_id', 'season', 'defense_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_defensive_tracking_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_defensive_tracking_team_id'), ['team_id'], unique=False)
        batch_op.create_index('ix_player_defensive_tracking_team_season', ['team_id', 'season'], unique=False)

    op.create_table('player_hustle_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('team_abbreviation', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('contested_shots_2pt', sa.Float(), nullable=True),
    sa.Column('contested_shots_3pt', sa.Float(), nullable=True),
    sa.Column('contested_shots', sa.Float(), nullable=True),
    sa.Column('deflections', sa.Float(), nullable=True),
    sa.Column('charges_drawn', sa.Float(), nullable=True),
    sa.Column('screen_assists', sa.Float(), nullable=True),
    sa.Column('screen_ast_pts', sa.Float(), nullable=True),
    sa.Column('loose_balls_recovered_off', sa.Float(), nullable=True),
    sa.Column('loose_balls_recovered_def', sa.Float(), nullable=True),
    sa.Column('loose_balls_recovered', sa.Float(), nullable=True),
    sa.Column('box_outs_off', sa.Float(), nullable=True),
    sa.Column('box_outs_def', sa.Float(), nullable=True),
    sa.Column('box_outs', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='uq_player_hustle_stats_player_season')
    )
    with op.batch_alter_table('player_hustle_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_hustle_stats_player_id'), ['player_id'], unique=False)
        batch_op.create_index('ix_player_hustle_stats_player_season', ['player_id', 'season'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_hustle_stats_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_hustle_stats_team_id'), ['team_id'], unique=False)
        batch_op.create_index('ix_player_hustle_stats_team_season', ['team_id', 'season'], unique=False)

    op.create_table('player_on_off_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('court_status', sa.String(), nullable=False),
    sa.Column('gp', sa.Integer(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('off_rating', sa.Float(), nullable=True),
    sa.Column('def_rating', sa.Float(), nullable=True),
    sa.Column('net_rating', sa.Float(), nullable=True),
    sa.Column('ast_pct', sa.Float(), nullable=True),
    sa.Column('ast_to', sa.Float(), nullable=True),
    sa.Column('ast_ratio', sa.Float(), nullable=True),
    sa.Column('oreb_pct', sa.Float(), nullable=True),
    sa.Column('dreb_pct', sa.Float(), nullable=True),
    sa.Column('reb_pct', sa.Float(), nullable=True),
    sa.Column('tov_pct', sa.Float(), nullable=True),
    sa.Column('efg_pct', sa.Float(), nullable=True),
    sa.Column('ts_pct', sa.Float(), nullable=True),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.Column('pie', sa.Float(), nullable=True),
    sa.Column('plus_minus', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'team_id', 'season', 'court_status', name='uq_player_on_off_stats_key')
    )
    with op.batch_alter_table('player_on_off_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_on_off_stats_player_id'), ['player_id'], unique=False)
        batch_op.create_index('ix_player_on_off_stats_player_season', ['player_id', 'season'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_on_off_stats_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_on_off_stats_team_id'), ['team_id'], unique=False)
        batch_op.create_index('ix_player_on_off_stats_team_season', ['team_id', 'season'], unique=False)

    op.create_table('player_play_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('team_abbreviation', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('play_type', sa.String(), nullable=False),
    sa.Column('type_grouping', sa.String(), nullable=False),
    sa.Column('gp', sa.Integer(), nullable=True),
    sa.Column('poss_pct', sa.Float(), nullable=True),
    sa.Column('ppp', sa.Float(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('ft_poss_pct', sa.Float(), nullable=True),
    sa.Column('tov_pct', sa.Float(), nullable=True),
    sa.Column('sf_pct', sa.Float(), nullable=True),
    sa.Column('plusone_pct', sa.Float(), nullable=True),
    sa.Column('score_pct', sa.Float(), nullable=True),
    sa.Column('efg_pct', sa.Float(), nullable=True),
    sa.Column('poss', sa.Float(), nullable=True),
    sa.Column('pts', sa.Float(), nullable=True),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'play_type', 'type_grouping', name='uq_player_play_types_key')
    )
    with op.batch_alter_table('player_play_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_play_types_player_id'), ['player_id'], unique=False)
        batch_op.create_index('ix_player_play_types_player_season_play_type', ['player_id', 'season', 'play_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_play_types_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_play_types_team_id'), ['team_id'], unique=False)
        batch_op.create_index('ix_player_play_types_team_season', ['team_id', 'season'], unique=False)

    op.create_table('player_shot_location_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('team_abbreviation', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('restricted_area_fgm', sa.Float(), nullable=True),
    sa.Column('restricted_area_fga', sa.Float(), nullable=True),
    sa.Column('restricted_area_fg_pct', sa.Float(), nullable=True),
    sa.Column('in_the_paint_fgm', sa.Float(), nullable=True),
    sa.Column('in_the_paint_fga', sa.Float(), nullable=True),
    sa.Column('in_the_paint_fg_pct', sa.Float(), nullable=True),
    sa.Column('mid_range_fgm', sa.Float(), nullable=True),
    sa.Column('mid_range_fga', sa.Float(), nullable=True),
    sa.Column('mid_range_fg_pct', sa.Float(), nullable=True),
    sa.Column('left_corner_3_fgm', sa.Float(), nullable=True),
    sa.Column('left_corner_3_fga', sa.Float(), nullable=True),
    sa.Column('left_corner_3_fg_pct', sa.Float(), nullable=True),
    sa.Column('right_corner_3_fgm', sa.Float(), nullable=True),
    sa.Column('right_corner_3_fga', sa.Float(), nullable=True),
    sa.Column('right_corner_3_fg_pct', sa.Float(), nullable=True),
    sa.Column('above_the_break_3_fgm', sa.Float(), nullable=True),
    sa.Column('above_the_break_3_fga', sa.Float(), nullable=True),
    sa.Column('above_the_break_3_fg_pct', sa.Float(), nullable=True),
    sa.Column('backcourt_fgm', sa.Float(), nullable=True),
    sa.Column('backcourt_fga', sa.Float(), nullable=True),
    sa.Column('backcourt_fg_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='uq_player_shot_location_stats_player_season')
    )
    with op.batch_alter_table('player_shot_location_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_shot_location_stats_player_id'), ['player_id'], unique=False)
        batch_op.create_index('ix_player_shot_location_stats_player_season', ['player_id', 'season'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_shot_location_stats_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_shot_location_stats_team_id'), ['team_id'], unique=False)
        batch_op.create_index('ix_player_shot_location_stats_team_season', ['team_id', 'season'], unique=False)

    op.create_table('player_tracking_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('team_abbreviation', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('measure_type', sa.String(), nullable=False),
    sa.Column('gp', sa.Integer(), nullable=True),
    sa.Column('g', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('fgm', sa.Float(), nullable=True),
    sa.Column('fga', sa.Float(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('fg3m', sa.Float(), nullable=True),
    sa.Column('fg3a', sa.Float(), nullable=True),
    sa.Column('fg3_pct', sa.Float(), nullable=True),
    sa.Column('efg_pct', sa.Float(), nullable=True),
    sa.Column('pts', sa.Float(), nullable=True),
    sa.Column('drives', sa.Float(), nullable=True),
    sa.Column('drive_fgm', sa.Float(), nullable=True),
    sa.Column('drive_fga', sa.Float(), nullable=True),
    sa.Column('drive_fg_pct', sa.Float(), nullable=True),
    sa.Column('drive_ftm', sa.Float(), nullable=True),
    sa.Column('drive_fta', sa.Float(), nullable=True),
    sa.Column('drive_ft_pct', sa.Float(), nullable=True),
    sa.Column('drive_pts', sa.Float(), nullable=True),
    sa.Column('drive_pts_pct', sa.Float(), nullable=True),
    sa.Column('drive_passes', sa.Float(), nullable=True),
    sa.Column('drive_passes_pct', sa.Float(), nullable=True),
    sa.Column('drive_ast', sa.Float(), nullable=True),
    sa.Column('drive_ast_pct', sa.Float(), nullable=True),
    sa.Column('drive_tov', sa.Float(), nullable=True),
    sa.Column('drive_tov_pct', sa.Float(), nullable=True),
    sa.Column('drive_pf', sa.Float(), nullable=True),
    sa.Column('drive_pf_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'measure_type', name='uq_player_tracking_stats_key')
    )
    with op.batch_alter_table('player_tracking_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_tracking_stats_player_id'), ['player_id'], unique=False)
        batch_op.create_index('ix_player_tracking_stats_player_measure', ['player_id', 'season', 'measure_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_tracking_stats_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_tracking_stats_team_id'), ['team_id'], unique=False)
        batch_op.create_index('ix_player_tracking_stats_team_season', ['team_id', 'season'], unique=False)

    op.create_table('shot_chart_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('shot_type', sa.String(), nullable=True),
    sa.Column('shot_zone_basic', sa.String(), nullable=True),
    sa.Column('shot_zone_area', sa.String(), nullable=True),
    sa.Column('shot_zone_range', sa.String(), nullable=True),
    sa.Column('shot_distance', sa.Float(), nullable=True),
    sa.Column('loc_x', sa.Float(), nullable=True),
    sa.Column('loc_y', sa.Float(), nullable=True),
    sa.Column('shot_made_flag', sa.Boolean(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('minutes_remaining', sa.Integer(), nullable=True),
    sa.Column('seconds_remaining', sa.Integer(), nullable=True),
    sa.Column('htm', sa.String(), nullable=True),
    sa.Column('vtm', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', 'period', 'minutes_remaining', 'seconds_remaining', 'loc_x', 'loc_y', name='uq_shot_chart_detail_event_location')
    )
    with op.batch_alter_table('shot_chart_details', schema=None) as batch_op:
        batch_op.create_index('ix_shot_chart_detail_game_player', ['game_id', 'player_id'], unique=False)
        batch_op.create_index('ix_shot_chart_detail_game_zone', ['game_id', 'shot_zone_basic'], unique=False)
        batch_op.create_index(batch_op.f('ix_shot_chart_details_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shot_chart_details_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shot_chart_details_shot_zone_basic'), ['shot_zone_basic'], unique=False)
        batch_op.create_index(batch_op.f('ix_shot_chart_details_team_id'), ['team_id'], unique=False)

    op.create_table('win_probability_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('event_num', sa.Integer(), nullable=False),
    sa.Column('home_pct', sa.Float(), nullable=True),
    sa.Column('visitor_pct', sa.Float(), nullable=True),
    sa.Column('home_pts', sa.Integer(), nullable=True),
    sa.Column('visitor_pts', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('seconds_remaining', sa.Float(), nullable=True),
    sa.Column('home_description', sa.Text(), nullable=True),
    sa.Column('visitor_description', sa.Text(), nullable=True),
    sa.Column('neutral_description', sa.Text(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'event_num', name='uq_win_probability_entry_game_event')
    )
    with op.batch_alter_table('win_probability_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_win_probability_entries_game_id'), ['game_id'], unique=False)
        batch_op.create_index('ix_win_probability_entry_game', ['game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('win_probability_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_win_probability_entry_game')
        batch_op.drop_index(batch_op.f('ix_win_probability_entries_game_id'))

    op.drop_table('win_probability_entries')
    with op.batch_alter_table('shot_chart_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shot_chart_details_team_id'))
        batch_op.drop_index(batch_op.f('ix_shot_chart_details_shot_zone_basic'))
        batch_op.drop_index(batch_op.f('ix_shot_chart_details_player_id'))
        batch_op.drop_index(batch_op.f('ix_shot_chart_details_game_id'))
        batch_op.drop_index('ix_shot_chart_detail_game_zone')
        batch_op.drop_index('ix_shot_chart_detail_game_player')

    op.drop_table('shot_chart_details')
    with op.batch_alter_table('player_tracking_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_player_tracking_stats_team_season')
        batch_op.drop_index(batch_op.f('ix_player_tracking_stats_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_tracking_stats_season'))
        batch_op.drop_index('ix_player_tracking_stats_player_measure')
        batch_op.drop_index(batch_op.f('ix_player_tracking_stats_player_id'))

    op.drop_table('player_tracking_stats')
    with op.batch_alter_table('player_shot_location_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_player_shot_location_stats_team_season')
        batch_op.drop_index(batch_op.f('ix_player_shot_location_stats_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_shot_location_stats_season'))
        batch_op.drop_index('ix_player_shot_location_stats_player_season')
        batch_op.drop_index(batch_op.f('ix_player_shot_location_stats_player_id'))

    op.drop_table('player_shot_location_stats')
    with op.batch_alter_table('player_play_types', schema=None) as batch_op:
        batch_op.drop_index('ix_player_play_types_team_season')
        batch_op.drop_index(batch_op.f('ix_player_play_types_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_play_types_season'))
        batch_op.drop_index('ix_player_play_types_player_season_play_type')
        batch_op.drop_index(batch_op.f('ix_player_play_types_player_id'))

    op.drop_table('player_play_types')
    with op.batch_alter_table('player_on_off_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_player_on_off_stats_team_season')
        batch_op.drop_index(batch_op.f('ix_player_on_off_stats_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_on_off_stats_season'))
        batch_op.drop_index('ix_player_on_off_stats_player_season')
        batch_op.drop_index(batch_op.f('ix_player_on_off_stats_player_id'))

    op.drop_table('player_on_off_stats')
    with op.batch_alter_table('player_hustle_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_player_hustle_stats_team_season')
        batch_op.drop_index(batch_op.f('ix_player_hustle_stats_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_hustle_stats_season'))
        batch_op.drop_index('ix_player_hustle_stats_player_season')
        batch_op.drop_index(batch_op.f('ix_player_hustle_stats_player_id'))

    op.drop_table('player_hustle_stats')
    with op.batch_alter_table('player_defensive_tracking', schema=None) as batch_op:
        batch_op.drop_index('ix_player_defensive_tracking_team_season')
        batch_op.drop_index(batch_op.f('ix_player_defensive_tracking_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_defensive_tracking_season'))
        batch_op.drop_index('ix_player_defensive_tracking_player_season_category')
        batch_op.drop_index(batch_op.f('ix_player_defensive_tracking_player_id'))

    op.drop_table('player_defensive_tracking')
    with op.batch_alter_table('player_clutch_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_player_clutch_stats_team_season')
        batch_op.drop_index(batch_op.f('ix_player_clutch_stats_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_clutch_stats_season'))
        batch_op.drop_index('ix_player_clutch_stats_player_season')
        batch_op.drop_index(batch_op.f('ix_player_clutch_stats_player_id'))

    op.drop_table('player_clutch_stats')
    with op.batch_alter_table('matchup_boxscores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matchup_boxscores_offense_player_id'))
        batch_op.drop_index(batch_op.f('ix_matchup_boxscores_game_id'))
        batch_op.drop_index(batch_op.f('ix_matchup_boxscores_defense_player_id'))
        batch_op.drop_index('ix_matchup_boxscore_game_offense')
        batch_op.drop_index('ix_matchup_boxscore_game_defense')

    op.drop_table('matchup_boxscores')
    with op.batch_alter_table('lineup_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_lineup_stats_team_season_group')
        batch_op.drop_index(batch_op.f('ix_lineup_stats_team_id'))
        batch_op.drop_index(batch_op.f('ix_lineup_stats_season'))
        batch_op.drop_index(batch_op.f('ix_lineup_stats_group_id'))

    op.drop_table('lineup_stats')
    with op.batch_alter_table('hustle_stats_boxscores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hustle_stats_boxscores_team_id'))
        batch_op.drop_index(batch_op.f('ix_hustle_stats_boxscores_player_id'))
        batch_op.drop_index(batch_op.f('ix_hustle_stats_boxscores_game_id'))
        batch_op.drop_index('ix_hustle_stats_boxscore_player_game')

    op.drop_table('hustle_stats_boxscores')
    # ### end Alembic commands ###
